# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node
        environment:
          BUNDLER_VERSION: 2.0.1
    steps:
      - checkout

      - run:
          name: "Dependency: install proper version of bundler"
          command: gem install bundler -v $BUNDLER_VERSION

      - run:
          name: "Dependency: bundle config"
          command: bundle config --local path ~/.vendor/bundler

      # Restore bundle cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache:
          name: "Dependency: restoring bundler cache"
          keys:
            - bundler-v5-{{ arch }}-{{ checksum "Gemfile.lock" }}
            - bundler-v5-{{ arch }}-

      - run: # Install Ruby dependencies
          name: "Dependency: bundle install"
          command: bundle check || bundle install

      # Store bundle cache for Ruby dependencies
      - save_cache:
          name: "Dependency: saving bundler cache"
          key: bundler-v5-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/.vendor/bundler

      - run:
          name: Building site
          command: bundle exec jekyll build

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  build:
    jobs:
      - build
